### ISSUE TITLE
argument --instance-id: expected one argument

### ISSUE THREAD

**Issue by kevleyski** [alicemara/Test#1]
Hi Alice - copy paste the issue I was showing you

An error occurred (InvalidParameterCombination) when calling the TerminateInstances operation: No instances specified
Waiting 30 seconds to allow any extra instances to terminate...
Now deleting unused elastic IPs...
We will create your SSH keys now. They will be named invisibli.pem. Any prior ones with the same name will be overwritten.
{
    "GroupId": "sg-02d2a4df66c8334ee"
}
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: --no-cli-pager
Giving the instance 30 seconds to get provisioned
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: --tag-specifications, ResourceType=elastic-ip,Tags=[{Key=server,Value=invisibli}]
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --instance-id: expected one argument

**Comment by alicemara** [comment]
Thanks for this info!

Dug through this and went through some testing. I was able to replicate these issues and I believe I found the source of the errors here.

I think two things happened:
1. We cut the first run of the script short, thus it didn't clear out the .txt files used for managing variables like it normally does at the end. Then when rerunning the script, it just added to them instead of using new ones, breaking the script. We can see that directly with the error: "aws: error: argument --instance-id: expected one argument" I believe we also didn't restart the shell to clear out enviroment variables as well (which I should have said). 

I'm going to test a few different ways to try to deal with this a little cleaner and will update once I figured out a better way to do so automatically. 

Whenever you have time, would you be willing to try rerunning in a fresh shell and make sure that no txt files are in the invisibli directory? This way we can make sure there's not some random other factor breaking things. :) Thanks Kev!

**Comment by kevleyski** [comment]
Yep all good, will test it later this week

**Comment by kevleyski** [comment]
Ah in my case my aws tools were too old - I'll play with this again at home on a fresh  VM
